Fixed SCOR reading & writing
ibs-pan/foodwebviz pull request #15
Opened 2023-04-27 17:51 UTC by mkjiskrz

In read_from_SCOR the part reading the flow list was actually reading only the first line, I have added the missing ':' in lines[x:].
In write_to_SCOR write_col() the to_csv somehow produced extra empty lines between records. Turned back to writelines. Curiously, the empty lines appeared only when calling the whole function and did not when using that line of code in separation. I have ignored this curiosity - the explicit solution works.

2023-04-27 18:26 UTC, lpawluczuk commented
Good catch with the `:`!

Are you sure about that extra lines in `to_csv`? I've looked at this and it seems fine.

2023-04-27 18:27 UTC, lpawluczuk requested changes

2023-04-27 18:27 UTC, lpawluczuk commented on foodwebviz/io.py
>  if __name__ == '__main__':
I think we should remove this part entirely.

2023-04-27 19:05 UTC, mkjiskrz commented on foodwebviz/io.py
>  if __name__ == '__main__':
You're right! I have removed it and added a new commit to this branch

2023-04-27 19:07 UTC, mkjiskrz commented
> Good catch with the `:`!
> 
> Are you sure about that extra lines in `to_csv`? I've looked at this and it seems fine.

It ::should:: be fine, but somehow it didn't work when the write_to_SCOR and the rest were run. I could not figure out why.

2023-05-06 07:39 UTC, lpawluczuk commented
I think it would be better to stick with the existing version. Would you mind trying one more time? I can look into it as well!

2023-05-10 09:14 UTC, lpawluczuk commented
@mkjiskrz It seems that .to_csv() might indeed be problematic in Windows. Let's this new version of code then.

2023-05-10 09:14 UTC, lpawluczuk approved these changes

2023-05-10 09:14 UTC, merged